spring:
  application:
    name: veiculo-api
  datasource: 
    url: jdbc:mysql://${DB_HOST:localhost}:3306/db_veiculo?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate: 
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  
  jackson: 
    deserialization: 
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  docker:
    compose: # Quando desabilitado necessario crio o container mysql para rodar aplicacao: docker container run -d -p 3307:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes --name veiculo-mysql mysql:8.0
      enabled: ${DOCKER_COMPOSE_ENABLED:true}
      

# CONFIGURA SERVIDOR    
server:
  port: ${SERVER_PORT:8081}
  address: 0.0.0.0
  servlet:
    context-path: /veiculo-api
  

# CONFIGURA SWAGGER SPRINGDOC 
springdoc:
  api-docs:
    path: /v3/api-docs #URL usada ​​para carregar o swagger ui deste serviço pelo gateway de API 
  swagger-ui:
    path: /swagger-ui.html